name: "🚀 Release Umbraco Package"
description: ""
author: "James Carter"
branding:
  icon: "refresh-cw"
  color: "gray-dark"
inputs:
  artifact-name:
    description: "Artifact name"
    required: true
  version:
    description: "Version"
    required: true
  nuget-api-key:
    description: "NuGet API key"
    required: true
  github-token:
    description: "GitHub token"
    required: true
  nuget-source:
    description: "NuGet source"
    default: "https://api.nuget.org/v3/index.json"
    required: false
runs:
  using: "composite"
  steps:
    - name: Set env
      id: set-env
      shell: bash
      run: |
        echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
        echo "ARTIFACT_NAME=${{ inputs.artifact-name }}" >> $GITHUB_ENV
        echo "NUGET_API_KEY=${{ inputs.nuget-api-key }}" >> $GITHUB_ENV
        echo "ARTIFACT_PATH=./packages" >> $GITHUB_ENV
        echo "NUGET_SOURCE=${{ inputs.nuget-source }}" >> $GITHUB_ENV
    - name: Download package
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.ARTIFACT_PATH }}
    - name: Push to NuGet
      shell: bash
      run: |
        dotnet nuget push ${{ env.ARTIFACT_PATH }}/**/*.nupkg -k ${{ env.NUGET_API_KEY }} -s ${{ env.NUGET_SOURCE }}
    - name: 🚀 Create release
      uses: jcdcdev/jcdcdev.GitHub.CreateRelease@main
      with:
        version: ${{ env.VERSION }}
        github-token: ${{ inputs.github-token }}
